---
- name: Create isucon group
  become: yes
  become_user: root
  group:
    name: isucon
    gid: 2001
    state: present
    system: no

- name: Create isucon user
  become: yes
  become_user: root
  user:
    name: isucon
    uid: 2001
    group: isucon
    password: isucon
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no

- name: Add sudoers
  become: yes
  become_user: root
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-user
    owner: root
    group: root
    mode: 0440

- name: Install epel-release
  become: yes
  become_user: root
  yum:
    pkg: ['epel-release']
    state: installed

- name: Install Development Tools
  become: yes
  become_user: root
  yum:
    pkg: ['@Development Tools']
    state: present

- name: Install packages
  become: yes
  become_user: root
  yum:
    pkg: ['autoconf', 'automake', 'curl', 'dstat', 'firewalld', 'gdbm-devel', 'git', 'jq', 'libffi-devel', 'libyaml-devel', 'ncurses-devel', 'openssl-devel', 'patch', 'readline-devel', 'sudo', 'zlib-devel']
    state: installed

- name: Restart and enable firewalld
  become: yes
  become_user: root
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Install xbuild
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/tagomoris/xbuild.git
    dest: /home/isucon/xbuild
    version: master

- name: mkdir /home/isucon/local for xbuild
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/local
    state=directory
